---
 - name: syncronize code
   synchronize: src=../{{ site_name }} dest=/var/www rsync_path="sudo rsync"

 - name: create virtualenv -- flaskbox
   pip: requirements=/var/www/{{ site_name }}/requirements.txt virtualenv=/var/www/{{ site_name }}/flaskbox

 - name: reset permissions
   file: dest=/var/www state=directory recurse=yes owner=www-data group=www-data mode=0755

#- name: Copy nginx default.conf
#  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#  notify: restart nginx