---
- name: Install nginx
  apt: name=nginx state=present

- name: Remove nginx default.conf
  file: path=/etc/nginx/sites-enabled/default state=absent

#- name: Copy nginx default.conf
#  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#  notify: restart nginx